spring.application.name=backend

# Configuration Base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/hijabshop?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Initialisation SQL (Désactivée pour conserver les modifications)
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
app.jwt.secret=HijabShopSuperSecretKey2026PleaseChangeInProduction!
app.jwt.expiration=86400000
